# Generated by Django 5.1.5 on 2025-01-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="BannerConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True)),
                ("text", models.CharField(max_length=200)),
                ("show_banner", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CookieGroup",
            fields=[
                ("cookie_id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("is_required", models.BooleanField()),
                ("version", models.PositiveBigIntegerField(default=0, editable=False)),
            ],
        ),
    )
